using Microsoft.Extensions.Logging.Abstractions;
using ReviewClips.Core.Analysis;
using ReviewClips.Core.Primitives;
using ReviewClips.Ffmpeg.Analysis;
using ReviewClips.Ffmpeg.Probe;

namespace ReviewClips.Ffmpeg.Tests.Integration;

[Collection(FfmpegTestGroup.Name)]
public class ProbeTests
{
    private readonly FfmpegFixture _fixture;

    public ProbeTests(FfmpegFixture fixture) => _fixture = fixture;

    private FfprobeMediaProbe Probe() =>
        new(_fixture.Runner, NullLogger<FfprobeMediaProbe>.Instance);

    [Fact]
    public async Task ReadsCoreStreamProperties()
    {
        Assert.SkipUnless(_fixture.Available, "FFmpeg is not installed.");

        var info = await Probe().ProbeAsync(_fixture.SimpleClip, TestContext.Current.CancellationToken);

        info.Width.ShouldBe(1280);
        info.Height.ShouldBe(720);
        info.FrameRate.ShouldBe(30d, 0.01);
        info.VideoCodec.ShouldBe("h264");
        info.PixelFormat.ShouldBe("yuv420p");
        info.Duration.TotalSeconds.ShouldBe(10d, 0.2);
        info.IsHdr.ShouldBeFalse();
        info.IsAnamorphic.ShouldBeFalse();
        info.FileSizeBytes.ShouldBeGreaterThan(0);
    }

    [Fact]
    public async Task DetectsAnamorphicSampleAspectRatio()
    {
        Assert.SkipUnless(_fixture.Available, "FFmpeg is not installed.");

        var info = await Probe().ProbeAsync(_fixture.AnamorphicClip, TestContext.Current.CancellationToken);

        info.IsAnamorphic.ShouldBeTrue();
        info.SampleAspectRatio.ShouldBe(new Ratio(32, 27));

        // 720x480 with SAR 32:27 displays as 16:9.
        info.DisplayAspectRatio.ShouldBe(16d / 9d, 0.01);
    }

    [Fact]
    public async Task ThrowsAClearErrorForAMissingFile()
    {
        Assert.SkipUnless(_fixture.Available, "FFmpeg is not installed.");

        await Should.ThrowAsync<FileNotFoundException>(() =>
            Probe().ProbeAsync("/nonexistent/nope.mp4", TestContext.Current.CancellationToken));
    }

    [Theory]
    [InlineData("24000/1001", 23.976)]
    [InlineData("30/1", 30)]
    [InlineData("25", 25)]
    public void ParsesRationalFrameRates(string input, double expected)
    {
        FfprobeMediaProbe.TryParseRational(input, out var value).ShouldBeTrue();
        value.ShouldBe(expected, 0.001);
    }

    [Theory]
    [InlineData("0/0")]
    [InlineData("")]
    [InlineData("abc")]
    public void RejectsUnusableFrameRates(string input) =>
        FfprobeMediaProbe.TryParseRational(input, out _).ShouldBeFalse();

    [Theory]
    [InlineData("0:1")]
    [InlineData("N/A")]
    [InlineData(null)]
    public void TreatsUnspecifiedSampleAspectRatioAsAbsent(string? input) =>
        // ffprobe emits 0:1 for "unspecified"; treating it as a real ratio would corrupt scaling.
        FfprobeMediaProbe.ParseRatio(input).ShouldBeNull();

    [Fact]
    public async Task ReadsNamedChapterMarkers()
    {
        Assert.SkipUnless(_fixture.Available, "FFmpeg is not installed.");

        var info = await Probe().ProbeAsync(_fixture.ChapteredClip, TestContext.Current.CancellationToken);

        info.HasChapters.ShouldBeTrue();
        info.HasNamedChapters.ShouldBeTrue();
        info.Chapters.Count.ShouldBe(4);

        info.Chapters.Select(c => c.Title)
            .ShouldBe(["Opening Titles", "Act One", "Act Two", "End Credits"]);

        // Indices are assigned in file order and the ranges tile the runtime.
        info.Chapters.Select(c => c.Index).ShouldBe([0, 1, 2, 3]);
        info.Chapters[0].Start.ShouldBe(TimeSpan.Zero);
        info.Chapters[0].End.TotalSeconds.ShouldBe(2d, 0.05);
        info.Chapters[3].Start.TotalSeconds.ShouldBe(8d, 0.05);

        for (var i = 0; i < info.Chapters.Count - 1; i++)
        {
            info.Chapters[i].End.ShouldBe(info.Chapters[i + 1].Start);
        }

        // No chapter may run past the reported duration, or it would exclude footage that
        // does not exist and skew the eligible-range arithmetic.
        info.Chapters[^1].End.ShouldBeLessThanOrEqualTo(info.Duration);
    }

    [Fact]
    public async Task RecognizesAutoGeneratedChapterNamesAsUnnamed()
    {
        Assert.SkipUnless(_fixture.Available, "FFmpeg is not installed.");

        var info = await Probe().ProbeAsync(_fixture.UnnamedChapterClip, TestContext.Current.CancellationToken);

        info.HasChapters.ShouldBeTrue();
        info.HasNamedChapters.ShouldBeFalse();
        info.Chapters.ShouldAllBe(c => c.MeaningfulTitle == null);
    }

    [Fact]
    public async Task ReportsNoChaptersForAPlainFile()
    {
        Assert.SkipUnless(_fixture.Available, "FFmpeg is not installed.");

        var info = await Probe().ProbeAsync(_fixture.SimpleClip, TestContext.Current.CancellationToken);

        info.Chapters.ShouldBeEmpty();
        info.HasChapters.ShouldBeFalse();
    }

    [Fact]
    public void ChapterParsing_AcceptsAZeroStart() =>
        // The first chapter legitimately starts at zero, unlike a stream duration of zero.
        FfprobeMediaProbe.ParseChapterSeconds("0.000000").ShouldBe(TimeSpan.Zero);

    [Theory]
    [InlineData("N/A")]
    [InlineData("")]
    [InlineData(null)]
    [InlineData("-1.5")]
    [InlineData("nan")]
    public void ChapterParsing_RejectsUnusableTimestamps(string? input) =>
        FfprobeMediaProbe.ParseChapterSeconds(input).ShouldBeNull();

    [Fact]
    public void ChapterResolution_DropsDegenerateEntriesAndClampsToDuration()
    {
        var raw = new List<FfprobeChapter>
        {
            Chapter("30", "60", "Second"),
            Chapter("0", "30", "First"),

            // Zero-length, reversed, unparseable, and running past the end of the file.
            Chapter("60", "60", "Empty"),
            Chapter("90", "80", "Backwards"),
            Chapter("N/A", "100", "Broken"),
            Chapter("60", "999", "Overlong"),
        };

        var chapters = FfprobeMediaProbe.ResolveChapters(raw, TimeSpan.FromSeconds(100));

        chapters.Select(c => c.Title).ShouldBe(["First", "Second", "Overlong"]);
        chapters.Select(c => c.Index).ShouldBe([0, 1, 2]);
        chapters[^1].End.ShouldBe(TimeSpan.FromSeconds(100));
    }

    [Fact]
    public void ChapterResolution_ReadsTheTitleTagCaseInsensitively()
    {
        var raw = new List<FfprobeChapter>
        {
            new()
            {
                StartTime = "0",
                EndTime = "10",
                Tags = System.Text.Json.JsonSerializer
                    .Deserialize<Dictionary<string, System.Text.Json.JsonElement>>(
                        """{"TITLE":"End Credits"}"""),
            },
        };

        FfprobeMediaProbe.ResolveChapters(raw, TimeSpan.FromSeconds(10))[0]
            .Title.ShouldBe("End Credits");
    }

    private static FfprobeChapter Chapter(string start, string end, string title) => new()
    {
        StartTime = start,
        EndTime = end,
        Tags = System.Text.Json.JsonSerializer
            .Deserialize<Dictionary<string, System.Text.Json.JsonElement>>(
                $$"""{"title":{{System.Text.Json.JsonSerializer.Serialize(title)}}}"""),
    };
}

[Collection(FfmpegTestGroup.Name)]
public class AnalyzerTests
{
    private readonly FfmpegFixture _fixture;

    public AnalyzerTests(FfmpegFixture fixture) => _fixture = fixture;

    private async Task<MediaAnalysis> AnalyzeAsync(string path, AnalysisSettings? settings = null)
    {
        var probe = new FfprobeMediaProbe(_fixture.Runner, NullLogger<FfprobeMediaProbe>.Instance);
        var analyzer = new FfmpegMediaAnalyzer(_fixture.Runner, NullLogger<FfmpegMediaAnalyzer>.Instance);

        var info = await probe.ProbeAsync(path, TestContext.Current.CancellationToken);

        return await analyzer.AnalyzeAsync(
            info,
            settings ?? new AnalysisSettings(),
            progress: null,
            TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task CapturesMotionSamplesAcrossTheWholeRuntime()
    {
        Assert.SkipUnless(_fixture.Available, "FFmpeg is not installed.");

        // Pins the metadata truncation regression: the fixture is built by concatenation, which
        // reinitializes the filter graph mid-stream, and writing metadata to a file lost
        // everything before the final reinit.
        var analysis = await AnalyzeAsync(_fixture.MultiShotClip);

        var samples = analysis.Motion.Samples;
        samples.ShouldNotBeEmpty();

        var duration = analysis.Duration.TotalSeconds;

        samples[0].AtSeconds.ShouldBeLessThan(1d);
        samples[^1].AtSeconds.ShouldBeGreaterThan(duration - 2d);

        // At 4 fps over ~20s we expect roughly 80 samples; allow generous slack.
        samples.Count.ShouldBeGreaterThan((int)(duration * 2));
    }

    [Fact]
    public async Task DetectsSceneCutsBetweenDistinctShots()
    {
        Assert.SkipUnless(_fixture.Available, "FFmpeg is not installed.");

        var analysis = await AnalyzeAsync(_fixture.MultiShotClip);

        // The fixture has four visually unrelated shots, so cuts must be found.
        analysis.SceneCuts.ShouldNotBeEmpty();
        analysis.SceneCuts.ShouldBeInOrder();
        analysis.SceneCuts.ShouldAllBe(c => c > TimeSpan.Zero && c <= analysis.Duration);
    }

    [Fact]
    public async Task DetectsThePlantedBlackStretch()
    {
        Assert.SkipUnless(_fixture.Available, "FFmpeg is not installed.");

        // The fixture holds 3s of black starting at 14s.
        var analysis = await AnalyzeAsync(_fixture.MultiShotClip);

        analysis.BlackRanges.ShouldNotBeEmpty();

        var black = analysis.BlackRanges[0];
        black.Start.TotalSeconds.ShouldBeInRange(13d, 15d);
        black.Duration.TotalSeconds.ShouldBeGreaterThan(1.5d);
    }

    [Fact]
    public async Task DerivesShotsThatTileTheWholeRuntime()
    {
        Assert.SkipUnless(_fixture.Available, "FFmpeg is not installed.");

        var analysis = await AnalyzeAsync(_fixture.MultiShotClip);
        var shots = analysis.Shots();

        shots.ShouldNotBeEmpty();
        shots[0].Start.ShouldBe(TimeSpan.Zero);
        shots[^1].End.ShouldBe(analysis.Duration);

        // Contiguous with no gaps or overlaps.
        for (var i = 0; i < shots.Count - 1; i++)
        {
            shots[i].End.ShouldBe(shots[i + 1].Start);
        }
    }

    [Fact]
    public async Task HonorsTheConfiguredSampleRate()
    {
        Assert.SkipUnless(_fixture.Available, "FFmpeg is not installed.");

        var sparse = await AnalyzeAsync(_fixture.SimpleClip, new AnalysisSettings { SampleFrameRate = 2 });
        var dense = await AnalyzeAsync(_fixture.SimpleClip, new AnalysisSettings { SampleFrameRate = 8 });

        dense.Motion.Count.ShouldBeGreaterThan(sparse.Motion.Count);
    }

    [Fact]
    public void FilterChain_WritesMetadataToStdoutNotAFile()
    {
        // A file target is silently truncated on filter-graph reinitialization.
        var chain = FfmpegMediaAnalyzer.BuildFilterChain(new AnalysisSettings());

        chain.ShouldContain("metadata=print:file=-");
        chain.ShouldContain("scdet=threshold=8");
        chain.ShouldContain("fps=4");
        chain.ShouldContain("scale=320:-2");
    }

    [Fact]
    public void Arguments_KeepLogLevelHighEnoughForDetectorOutput()
    {
        var info = new ReviewClips.Core.Media.MediaInfo
        {
            Path = "/movies/x.mkv",
            FileSizeBytes = 1,
            LastModifiedUtc = DateTimeOffset.UnixEpoch,
            Duration = TimeSpan.FromMinutes(10),
            Width = 1920,
            Height = 1080,
            FrameRate = 24,
            VideoCodec = "h264",
            PixelFormat = "yuv420p",
            SampleAspectRatio = Ratio.One,
            HasAudio = false,
        };

        var arguments = FfmpegMediaAnalyzer.BuildArguments(info, new AnalysisSettings());

        // scdet, blackdetect and freezedetect report at info level; -loglevel error would
        // discard every one of them and the analysis would silently find nothing.
        arguments.ShouldNotContain("error");
        arguments.ShouldContain("-an");
        arguments.ShouldContain("-sn");
    }
}
