<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>rcc</AssemblyName>
    <RootNamespace>ReviewClips.Cli</RootNamespace>
    <RollForward>latestMinor</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReviewClips.Core\ReviewClips.Core.csproj" />
    <ProjectReference Include="..\ReviewClips.Ffmpeg\ReviewClips.Ffmpeg.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
